version: '3'
services:
  agent.broker.zookeeper:
    image: wurstmeister/zookeeper
    container_name: agent.broker.zookeeper
    ports:
      - "2181:2181"

  agent.broker.kafka:
    image: wurstmeister/kafka
    container_name: agent.broker.kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_name:1:1"
    depends_on:
      - agent.broker.zookeeper

  agent.broker.rabbitmq:
    container_name: agent.broker.rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=islab
      - RABBITMQ_DEFAULT_PASS=islab
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    restart: unless-stopped
    image: 'rabbitmq:management'
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
