version: '3'
services:
  agent.database.mariadb:
    container_name: agent.database.mariadb
    image: mariadb
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysqldata/conf.d:/etc/mysql/conf.d
      - ./mysqldata/data:/var/lib/mysql
      - ./mysqldata/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    

  agent.database.mongodb:
    container_name: agent.database.mongodb
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=L1954tp!