server:
  port: 8080
  url: https://smartcity.islab.dev/api/v1
  servlet:
    context-path: /v1

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: smartcitylab-agent
  data:
    mongodb:
      host: mongo
      database: agent
      port: 27017
      username: user
      password: pwd
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://smartcityLabMariaDB:3306/smartcitylab-agent
    username: islab
    password: islab

mqtt:
  broker:
    host: rabbitmq
    port: 1883
    topic: mytopic
  username: islab
  password: islab

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    show-actuator: true
    doc-expansion: none
    tags-sorter: alpha
    display-request-duration: true
    operations-sorter: method
  version: v0.0.1

---
server:
  port: 8080
  url: http://localhost:8080/api/v1
  servlet:
    context-path: /api/v1

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: smartcitylab-agent
  data:
    mongodb:
      host: mongo
      database: agent
      port: 27017
      username: user
      password: pwd
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://smartcityLabMariaDB:3306/smartcitylab-agent
    username: islab
    password: islab

mqtt:
  broker:
    host: rabbitmq
    port: 1883
    topic: mytopic
  username: islab
  password: islab

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    show-actuator: true
    doc-expansion: none
    tags-sorter: alpha
    display-request-duration: true
    operations-sorter: method
  version: v0.0.1
