server:
  port: 8080
  url: http://localhost:8080


spring:
  data:
    mongodb:
      host: localhost
      database: agent
      port: 27017
      username: user
      password: pwd
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/smartcitylab-agent
    username: user
    password: pwd

mqtt:
  broker:
    host: localhost
    port: 1883
    topic: mytopic
  username: user
  password: pwd

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    show-actuator: true
    doc-expansion: none
    tags-sorter: alpha
    display-request-duration: true
    operations-sorter: method
  version: v0.0.1

