server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      database: mqtt-sample
      port: 27017
      username: username
      password: password
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/database_nm
    username: username
    password: password

mqtt:
  broker:
    host: localhost
    port: 1883
    topic: topicname

springdoc:
  swagger-ui:
    path: /swagger-ui
    show-actuator: true
  version: v0.0.1

